/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiPublicHooksPublishScheduledRouteImport } from './routes/api/public/hooks/publish-scheduled'
import { Route as ApiPublicHooksSyncDriveFacebookRouteImport } from './routes/api/public/hooks/sync-drive-facebook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPublishScheduledRoute =
  ApiPublicHooksPublishScheduledRouteImport.update({
    id: '/api/public/hooks/publish-scheduled',
    path: '/api/public/hooks/publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncDriveFacebookRoute =
  ApiPublicHooksSyncDriveFacebookRouteImport.update({
    id: '/api/public/hooks/sync-drive-facebook',
    path: '/api/public/hooks/sync-drive-facebook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/hooks/sync-drive-facebook': typeof ApiPublicHooksSyncDriveFacebookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/hooks/sync-drive-facebook': typeof ApiPublicHooksSyncDriveFacebookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/hooks/sync-drive-facebook': typeof ApiPublicHooksSyncDriveFacebookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/status'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/hooks/sync-drive-facebook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/status'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/hooks/sync-drive-facebook'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/status'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/hooks/sync-drive-facebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  ApiPublicHooksPublishScheduledRoute: typeof ApiPublicHooksPublishScheduledRoute
  ApiPublicHooksSyncDriveFacebookRoute: typeof ApiPublicHooksSyncDriveFacebookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-scheduled': {
      id: '/api/public/hooks/publish-scheduled'
      path: '/api/public/hooks/publish-scheduled'
      fullPath: '/api/public/hooks/publish-scheduled'
      preLoaderRoute: typeof ApiPublicHooksPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-drive-facebook': {
      id: '/api/public/hooks/sync-drive-facebook'
      path: '/api/public/hooks/sync-drive-facebook'
      fullPath: '/api/public/hooks/sync-drive-facebook'
      preLoaderRoute: typeof ApiPublicHooksSyncDriveFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  ApiPublicHooksPublishScheduledRoute: ApiPublicHooksPublishScheduledRoute,
  ApiPublicHooksSyncDriveFacebookRoute: ApiPublicHooksSyncDriveFacebookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
